spring:
  datasource:
    url: jdbc:postgresql://localhost/bolton
    username: bolton
    password: bolton
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

io:
  mywish:
    airdrop:
      web3-url: http://localhost:8545/
      adminAddress: 0xB11c168fD4682946975361222fFb09909Ad045a3
      admin-password: 123
      contract-addresses:
        - 0xB11c168fD4682946975361222fFb09909Ad045a3
        - 0x1b22c32cd936cb97c28c5690a0695a82abf688e6
        - 0x69cda6099f211e608638964466d4ca65cd6bf993
      start-block: 4571374
